"""Centralised rights data for all supported countries."""

COUNTRY_NAMES = {
    "us": "United States",
    "sg": "Singapore",
    "my": "Malaysia",
    "id": "Indonesia",
    "ph": "Philippines",
    "th": "Thailand",
}

RIGHTS_BY_COUNTRY = {
    # ──────────────────────────────────────────────────────────────
    # UNITED STATES  (10 categories)
    # ──────────────────────────────────────────────────────────────
    "us": [
        {
            "id": "discrimination",
            "title": "Anti-Discrimination Protections",
            "summary": "Protection against workplace discrimination based on protected characteristics.",
            "details": [
                "Employers cannot discriminate based on race, color, religion, sex, national origin, age, disability, or genetic information.",
                "Equal pay for substantially similar work regardless of gender.",
                "Reasonable accommodations must be provided for disabilities and religious practices.",
                "Hiring, firing, promotion, and compensation decisions must be based on merit.",
            ],
            "what_to_do": "Document specific instances with dates, witnesses, and any written communications. File a complaint through this app or contact the EEOC.",
            "enforcement_agency": "Equal Employment Opportunity Commission (EEOC)",
            "agency_contact": "1-800-669-4000 | info@eeoc.gov | www.eeoc.gov",
            "penalties": [
                "Back pay and front pay for lost earnings.",
                "Compensatory damages up to $300,000 depending on employer size.",
                "Punitive damages for intentional discrimination.",
                "Attorney fees and court costs.",
            ],
            "key_laws": [
                {"name": "Title VII of the Civil Rights Act of 1964", "scope": "Employers with 15+ employees; race, color, religion, sex, national origin"},
                {"name": "Age Discrimination in Employment Act (ADEA)", "scope": "Employers with 20+ employees; workers aged 40+"},
                {"name": "Americans with Disabilities Act (ADA)", "scope": "Employers with 15+ employees; qualified individuals with disabilities"},
                {"name": "Equal Pay Act of 1963", "scope": "All employers; pay equity regardless of sex"},
                {"name": "Genetic Information Nondiscrimination Act (GINA)", "scope": "Employers with 15+ employees; genetic information"},
            ],
            "effective_date": "Various — Title VII: 1964, ADA: 1990, GINA: 2008",
            "faq": [
                {"q": "How long do I have to file a discrimination charge?", "a": "Generally 180 days from the discriminatory act, extended to 300 days in states with their own anti-discrimination agency."},
                {"q": "Does my employer have to have a certain number of employees?", "a": "Title VII and ADA apply to employers with 15 or more employees. ADEA applies to employers with 20 or more."},
                {"q": "Can I sue my employer directly?", "a": "You must first file a charge with the EEOC and obtain a Right to Sue letter before filing a federal lawsuit."},
            ],
            "case_examples": [
                "An employee is passed over for promotion despite superior qualifications because of their national origin — this may constitute discrimination under Title VII.",
                "A job applicant is asked about their plans to have children during an interview — this may violate sex discrimination protections.",
                "An employer refuses to allow schedule adjustments for an employee's religious observances — this may violate Title VII's religious accommodation requirement.",
            ],
        },
        {
            "id": "retaliation",
            "title": "Whistleblower & Retaliation Protections",
            "summary": "You cannot be punished for reporting violations or exercising your rights.",
            "details": [
                "Employers cannot retaliate against employees who report workplace violations.",
                "Protection covers filing complaints, participating in investigations, or refusing illegal orders.",
                "Retaliation includes termination, demotion, pay cuts, schedule changes, or hostile treatment.",
                "Protections apply even if the original complaint is not ultimately upheld.",
            ],
            "what_to_do": "Keep a timeline of events showing the connection between your protected activity and the adverse action. Save all communications.",
            "enforcement_agency": "EEOC / OSHA / Department of Labor (depending on type of retaliation)",
            "agency_contact": "EEOC: 1-800-669-4000 | OSHA Whistleblower: 1-800-321-6742",
            "penalties": [
                "Reinstatement to former position.",
                "Back pay with interest.",
                "Compensatory and punitive damages.",
                "Special damages such as emotional distress in some jurisdictions.",
            ],
            "key_laws": [
                {"name": "Title VII of the Civil Rights Act of 1964 (anti-retaliation provision)", "scope": "Retaliation for EEO activity"},
                {"name": "Sarbanes-Oxley Act (SOX)", "scope": "Publicly traded companies; financial fraud whistleblowers"},
                {"name": "Dodd-Frank Wall Street Reform Act", "scope": "SEC whistleblowers with financial incentives"},
                {"name": "OSHA Section 11(c)", "scope": "Workplace safety whistleblowers"},
            ],
            "effective_date": "Various — SOX: 2002, Dodd-Frank: 2010",
            "faq": [
                {"q": "What counts as retaliation?", "a": "Any adverse action — firing, demotion, pay cut, reassignment, or even social ostracism — taken because you engaged in protected activity."},
                {"q": "Do I have to prove my original complaint was valid?", "a": "No. You are protected from retaliation even if your complaint is ultimately not upheld, as long as you had a reasonable good-faith belief."},
            ],
            "case_examples": [
                "An employee is demoted shortly after filing an EEOC complaint — the timing suggests possible retaliation.",
                "A worker reports safety violations to OSHA and is subsequently assigned undesirable shifts — this may constitute retaliation under OSHA Section 11(c).",
            ],
        },
        {
            "id": "wages",
            "title": "Wage & Hour Rights",
            "summary": "Your right to fair compensation for all hours worked.",
            "details": [
                "Minimum wage and overtime protections for eligible workers.",
                "Employers must pay for all hours worked, including required training and travel time.",
                "Pay stubs must be provided with detailed breakdowns.",
                "Final paychecks must be issued within the timeframe required by state law.",
            ],
            "what_to_do": "Keep your own records of hours worked. Compare pay stubs against actual hours. Report discrepancies promptly.",
            "enforcement_agency": "Wage and Hour Division (WHD), U.S. Department of Labor",
            "agency_contact": "1-866-487-9243 | www.dol.gov/agencies/whd",
            "penalties": [
                "Back wages for unpaid overtime or minimum wage violations.",
                "Liquidated damages equal to the amount of back wages.",
                "Civil penalties up to $2,584 per violation for repeated or wilful violations.",
                "Criminal penalties for wilful violations (fines up to $10,000 and/or imprisonment).",
            ],
            "key_laws": [
                {"name": "Fair Labor Standards Act (FLSA)", "scope": "Federal minimum wage ($7.25/hr), overtime (1.5x after 40 hrs/week), child labour"},
                {"name": "State wage and hour laws", "scope": "May exceed FLSA protections (e.g. higher minimum wage, daily overtime)"},
            ],
            "effective_date": "FLSA: 1938 (amended regularly)",
            "faq": [
                {"q": "Am I entitled to overtime pay?", "a": "Non-exempt employees must receive overtime pay at 1.5 times their regular rate for hours over 40 per workweek. Exemptions apply to certain salaried professional, administrative, and executive employees."},
                {"q": "Can my employer deduct money from my paycheck?", "a": "Deductions cannot bring your pay below minimum wage. Certain deductions (like for cash register shortages) are restricted."},
            ],
            "case_examples": [
                "An employer requires employees to work through lunch but does not count it as hours worked — this likely violates FLSA.",
                "A tipped employee's tips plus base wage do not reach the minimum wage and the employer fails to make up the difference — this violates the FLSA tip credit provision.",
            ],
        },
        {
            "id": "safety",
            "title": "Workplace Safety",
            "summary": "Your right to a safe and healthy work environment.",
            "details": [
                "Employers must provide a workplace free from recognized hazards.",
                "You have the right to request an OSHA inspection without retaliation.",
                "Access to training, safety equipment, and injury/illness records.",
                "Right to refuse work that poses imminent danger to life or health.",
            ],
            "what_to_do": "Report hazards to your supervisor in writing. If unresolved, file a complaint with OSHA. Document unsafe conditions with photos and dates.",
            "enforcement_agency": "Occupational Safety and Health Administration (OSHA)",
            "agency_contact": "1-800-321-6742 | www.osha.gov",
            "penalties": [
                "Serious violations: up to $17,004 per violation.",
                "Wilful or repeated violations: up to $170,046 per violation.",
                "Failure to abate: up to $17,004 per day beyond abatement date.",
            ],
            "key_laws": [
                {"name": "Occupational Safety and Health Act of 1970 (OSH Act)", "scope": "Most private-sector employers; general duty clause and specific standards"},
            ],
            "effective_date": "1970",
            "faq": [
                {"q": "Can I refuse to work if conditions are unsafe?", "a": "You may refuse if you believe you face imminent danger of death or serious injury, you have asked the employer to correct the hazard, and there is no reasonable alternative."},
                {"q": "Can my employer fire me for reporting safety concerns?", "a": "No. Section 11(c) of the OSH Act prohibits retaliation for reporting safety concerns or filing OSHA complaints."},
            ],
            "case_examples": [
                "A construction worker is told to work at height without fall protection — this violates OSHA fall protection standards.",
                "An employer fails to provide proper ventilation in a chemical storage area — this may violate OSHA's hazard communication standard.",
            ],
        },
        {
            "id": "leave",
            "title": "Leave & Accommodations",
            "summary": "Your right to medical leave, family leave, and reasonable accommodations.",
            "details": [
                "FMLA provides up to 12 weeks of unpaid, job-protected leave for qualifying reasons.",
                "Employers must engage in an interactive process for disability accommodations.",
                "Pregnancy-related accommodations must be provided.",
                "You cannot be penalized for using legally protected leave.",
            ],
            "what_to_do": "Request accommodations or leave in writing. Keep copies of medical documentation you submit. Note your employer's response and timeline.",
            "enforcement_agency": "Wage and Hour Division (WHD) for FMLA; EEOC for ADA accommodations",
            "agency_contact": "WHD: 1-866-487-9243 | EEOC: 1-800-669-4000",
            "penalties": [
                "FMLA: back pay, benefits, reinstatement, and liquidated damages.",
                "ADA: compensatory and punitive damages up to $300,000.",
            ],
            "key_laws": [
                {"name": "Family and Medical Leave Act (FMLA)", "scope": "Employers with 50+ employees within 75 miles; 12 weeks unpaid leave"},
                {"name": "Americans with Disabilities Act (ADA)", "scope": "Employers with 15+ employees; reasonable accommodation"},
                {"name": "Pregnant Workers Fairness Act (PWFA)", "scope": "Employers with 15+ employees; reasonable accommodation for pregnancy-related conditions"},
            ],
            "effective_date": "FMLA: 1993, ADA: 1990, PWFA: 2023",
            "faq": [
                {"q": "Am I eligible for FMLA leave?", "a": "You must have worked for your employer for at least 12 months, have at least 1,250 hours of service in the previous 12 months, and work at a location with 50+ employees within a 75-mile radius."},
                {"q": "What is a 'reasonable accommodation'?", "a": "Any modification to the job or workplace that enables a qualified person with a disability to perform essential functions — e.g., modified schedule, ergonomic equipment, reassignment."},
            ],
            "case_examples": [
                "An employee requests FMLA leave to care for a newborn and is told they will lose their position — this likely violates FMLA.",
                "An employer refuses to consider allowing an employee with a mobility impairment to work from home — this may violate the ADA interactive process requirement.",
            ],
        },
        {
            "id": "harassment",
            "title": "Workplace Harassment Protections",
            "summary": "Protection against hostile work environment and quid pro quo harassment.",
            "details": [
                "Harassment based on protected characteristics (race, sex, religion, etc.) is illegal when it creates a hostile or intimidating work environment.",
                "Quid pro quo harassment occurs when employment decisions are conditioned on submission to unwelcome conduct.",
                "Employers are liable for harassment by supervisors and may be liable for harassment by co-workers if they knew or should have known and failed to act.",
                "Employers must take prompt corrective action when harassment is reported.",
                "Both men and women can be victims, and harassment can occur between people of the same sex.",
            ],
            "what_to_do": "Document every incident with dates, times, locations, witnesses, and details. Report to HR or management in writing. If the employer fails to act, file a charge with the EEOC.",
            "enforcement_agency": "Equal Employment Opportunity Commission (EEOC)",
            "agency_contact": "1-800-669-4000 | info@eeoc.gov | www.eeoc.gov",
            "penalties": [
                "Compensatory damages for emotional distress.",
                "Punitive damages for employer indifference or recklessness.",
                "Back pay and front pay.",
                "Injunctive relief (e.g., mandatory training, policy changes).",
            ],
            "key_laws": [
                {"name": "Title VII of the Civil Rights Act of 1964", "scope": "Harassment based on race, color, religion, sex, national origin"},
                {"name": "ADA", "scope": "Harassment based on disability"},
                {"name": "ADEA", "scope": "Harassment based on age (40+)"},
            ],
            "effective_date": "Title VII: 1964; harassment case law developed from 1986 (Meritor v. Vinson)",
            "faq": [
                {"q": "What makes behaviour 'harassment' legally?", "a": "Isolated incidents (unless extremely serious) generally do not constitute harassment. The conduct must be severe or pervasive enough to create a hostile or abusive working environment."},
                {"q": "Do I have to report to my employer before filing with the EEOC?", "a": "It is strongly recommended to use internal complaint procedures first, as it may affect the employer's liability. However, it is not a legal prerequisite to filing an EEOC charge."},
            ],
            "case_examples": [
                "A supervisor makes repeated sexually suggestive comments and the employer takes no action after complaints — this may constitute hostile work environment harassment.",
                "An employee is subjected to racial slurs and offensive jokes on a daily basis — this is likely severe and pervasive enough to be actionable harassment.",
            ],
        },
        {
            "id": "family_medical",
            "title": "Family & Medical Leave",
            "summary": "Job-protected leave for serious health conditions, new children, and military family needs.",
            "details": [
                "Up to 12 weeks of unpaid, job-protected leave per year for birth/adoption, serious health condition of self or family member.",
                "Up to 26 weeks of military caregiver leave to care for a covered service member.",
                "Health insurance must be maintained during FMLA leave on the same terms as if actively working.",
                "Employers may require medical certification for health-related leave.",
                "Intermittent leave is available when medically necessary.",
                "State laws may provide additional or paid family leave (e.g., California PFL, New York PFL).",
            ],
            "what_to_do": "Provide 30 days' advance notice when possible. Complete required certification forms. Keep copies of all submissions and employer responses.",
            "enforcement_agency": "Wage and Hour Division, U.S. Department of Labor",
            "agency_contact": "1-866-487-9243 | www.dol.gov/agencies/whd/fmla",
            "penalties": [
                "Back pay and lost benefits.",
                "Reinstatement or front pay.",
                "Liquidated damages equal to back pay for wilful violations.",
                "Attorney fees and costs.",
            ],
            "key_laws": [
                {"name": "Family and Medical Leave Act (FMLA)", "scope": "Employers with 50+ employees; 12/26 weeks leave"},
                {"name": "State family leave laws", "scope": "Vary by state — some provide paid leave and broader eligibility"},
            ],
            "effective_date": "1993",
            "faq": [
                {"q": "Can my employer deny FMLA leave?", "a": "If you meet eligibility requirements and have a qualifying reason, your employer cannot deny leave. They can request medical certification."},
                {"q": "Can I take FMLA intermittently?", "a": "Yes, when medically necessary — for example, periodic treatments or flare-ups of a chronic condition."},
            ],
            "case_examples": [
                "An employee with a chronic condition needs time off for periodic medical appointments — intermittent FMLA leave applies.",
                "A new parent is told they cannot return to the same or equivalent position after FMLA leave — this violates FMLA reinstatement rights.",
            ],
        },
        {
            "id": "privacy",
            "title": "Workplace Privacy",
            "summary": "Your privacy rights regarding monitoring, personal information, and medical records.",
            "details": [
                "Employers generally can monitor company-owned devices and email but must disclose monitoring policies.",
                "Medical records and genetic information must be kept confidential and separate from personnel files.",
                "Drug testing laws vary by state — some restrict when and how employers can test.",
                "Social media privacy laws in many states restrict employers from requiring access to personal accounts.",
                "Background checks require written consent under the Fair Credit Reporting Act (FCRA).",
            ],
            "what_to_do": "Review your employer's monitoring and privacy policies. Keep personal communications on personal devices. Request a copy of any background check results.",
            "enforcement_agency": "Federal Trade Commission (FTC) for FCRA; EEOC for medical privacy under ADA/GINA",
            "agency_contact": "FTC: 1-877-382-4357 | EEOC: 1-800-669-4000",
            "penalties": [
                "FCRA: statutory damages of $100–$1,000 per violation plus punitive damages.",
                "ADA medical confidentiality: standard ADA remedies including compensatory damages.",
                "State privacy law penalties vary.",
            ],
            "key_laws": [
                {"name": "Fair Credit Reporting Act (FCRA)", "scope": "Background checks and consumer reports for employment purposes"},
                {"name": "Electronic Communications Privacy Act (ECPA)", "scope": "Interception of electronic communications; employer monitoring with notice"},
                {"name": "ADA confidentiality provisions", "scope": "Medical information must be kept confidential"},
                {"name": "State privacy and social media laws", "scope": "Varies by state"},
            ],
            "effective_date": "FCRA: 1970, ECPA: 1986",
            "faq": [
                {"q": "Can my employer read my personal email on a work computer?", "a": "Generally yes, if they have disclosed their monitoring policy. Avoid using work devices for personal communications."},
                {"q": "Can my employer require a drug test?", "a": "It depends on your state. Some states allow pre-employment testing but restrict random testing. Federal contractors may have additional requirements."},
            ],
            "case_examples": [
                "An employer runs a background check without obtaining written consent — this violates FCRA requirements.",
                "A manager shares an employee's medical diagnosis with co-workers — this may violate ADA confidentiality provisions.",
            ],
        },
        {
            "id": "contracts",
            "title": "Employment Contracts & At-Will Doctrines",
            "summary": "Understanding your employment relationship, contract terms, and at-will exceptions.",
            "details": [
                "Most US employment is at-will — either party can end the relationship at any time for any lawful reason.",
                "At-will exceptions: implied contracts (e.g., employee handbook promises), public policy violations, and covenant of good faith.",
                "Non-compete agreements must be reasonable in scope, duration, and geography to be enforceable (rules vary by state).",
                "Severance agreements often include waiver of legal claims — you generally have 21 days to review and 7 days to revoke.",
                "Independent contractor misclassification can deny you benefits and protections you are entitled to.",
            ],
            "what_to_do": "Read all employment documents carefully before signing. Consult an attorney before signing non-competes or severance agreements. Keep copies of all signed agreements.",
            "enforcement_agency": "Department of Labor (misclassification); State attorneys general; courts (contract disputes)",
            "agency_contact": "DOL: 1-866-487-9243 | State labor agencies vary",
            "penalties": [
                "Misclassification: back taxes, benefits, and penalties for employers.",
                "Breach of contract: damages as specified in the contract or determined by court.",
            ],
            "key_laws": [
                {"name": "At-will employment doctrine", "scope": "Default in all states except Montana"},
                {"name": "State non-compete statutes", "scope": "Varies — California bans non-competes; others require reasonableness"},
                {"name": "Older Workers Benefit Protection Act (OWBPA)", "scope": "Severance waiver requirements for workers 40+"},
            ],
            "effective_date": "Various",
            "faq": [
                {"q": "Can I be fired for no reason?", "a": "In at-will states (most of the US), yes — but you cannot be fired for an illegal reason (discrimination, retaliation, etc.)."},
                {"q": "Is my non-compete enforceable?", "a": "It depends on your state and the agreement's terms. Some states (like California) generally do not enforce non-competes."},
            ],
            "case_examples": [
                "An employee is fired after refusing to participate in illegal activity — this may violate the public policy exception to at-will employment.",
                "A company classifies full-time workers as independent contractors to avoid providing benefits — this is misclassification.",
            ],
        },
        {
            "id": "labor_relations",
            "title": "National Labor Relations Act (NLRA)",
            "summary": "Protects employees' rights to organise, form unions, and bargain collectively.",
            "details": [
                "Employees have the right to form, join, or assist labour unions and to bargain collectively (Section 7).",
                "Employees also have the right to refrain from union activity.",
                "Employers cannot interfere with, restrain, or coerce employees exercising union rights.",
                "Employers cannot discriminate against employees for union membership or activity.",
                "Both employers and unions must bargain in good faith over wages, hours, and working conditions.",
                "Strikes are protected concerted activity, though secondary strikes and boycotts are prohibited.",
                "Right-to-work laws in some states prohibit mandatory union membership as a condition of employment.",
            ],
            "what_to_do": "File an unfair labor practice charge with the NLRB regional office within 6 months of the violation. The NLRB investigates and can issue complaints.",
            "enforcement_agency": "National Labor Relations Board (NLRB)",
            "agency_contact": "1-844-762-6572 | www.nlrb.gov",
            "penalties": [
                "Reinstatement of wrongfully terminated employees.",
                "Back pay with interest for lost wages.",
                "Cease-and-desist orders against unfair labour practices.",
                "Posting of notices informing employees of their rights.",
            ],
            "key_laws": [
                {"name": "National Labor Relations Act (Wagner Act, 1935)", "scope": "Private-sector employees' right to organise and bargain collectively"},
                {"name": "Labor Management Relations Act (Taft-Hartley Act, 1947)", "scope": "Union unfair labour practices, secondary boycott ban, right-to-work"},
                {"name": "Labor-Management Reporting and Disclosure Act (Landrum-Griffin Act, 1959)", "scope": "Union transparency, member rights within unions"},
            ],
            "effective_date": "1935 (NLRA); amended 1947 (Taft-Hartley), 1959 (Landrum-Griffin)",
            "faq": [
                {"q": "Does the NLRA cover all workers?", "a": "No. It excludes government employees, agricultural labourers, domestic workers, independent contractors, and supervisors."},
                {"q": "Can my employer fire me for union activity?", "a": "No. Termination for union activity is an unfair labour practice. File a charge with the NLRB within 6 months."},
                {"q": "What is a right-to-work state?", "a": "A state where employees cannot be required to join or pay dues to a union as a condition of employment."},
            ],
            "case_examples": [
                "An employer threatens to close the business if workers vote to unionise — this violates Section 8(a)(1) of the NLRA.",
                "A worker is fired shortly after leading a union organising effort — this is likely an unfair labour practice under Section 8(a)(3).",
            ],
        },
    ],

    # ──────────────────────────────────────────────────────────────
    # SINGAPORE  (10 categories)
    # ──────────────────────────────────────────────────────────────
    "sg": [
        {
            "id": "employment_act",
            "title": "Employment Act (Cap. 91)",
            "summary": "Singapore's main employment legislation covering wages, hours, leave, and termination.",
            "details": [
                "Covers all employees under a contract of service except seafarers, domestic workers, and public servants.",
                "Maximum 44 working hours per week (or 88 hours over 2 weeks). Overtime capped at 72 hours per month.",
                "Overtime pay at 1.5x the hourly basic rate for non-workmen earning up to S$2,600/month.",
                "Minimum 7 days annual leave after 3 months, increasing to 14 days after 8 years.",
                "11 paid public holidays per year. Sick leave: 14 days outpatient, 60 days hospitalisation.",
                "Employers must issue itemised payslips and key employment terms within 14 days of employment.",
            ],
            "what_to_do": "Keep copies of your employment contract and payslips. Report disputes to the Ministry of Manpower (MOM) or file a claim at the Employment Claims Tribunal.",
            "enforcement_agency": "Ministry of Manpower (MOM)",
            "agency_contact": "6438 5122 | www.mom.gov.sg",
            "penalties": [
                "Fines up to S$5,000 for first offence; up to S$10,000 for repeat offences.",
                "Imprisonment up to 6 months for wilful non-compliance.",
                "Court orders to pay outstanding wages.",
            ],
            "key_laws": [
                {"name": "Employment Act (Cap. 91)", "scope": "All employees under a contract of service (with limited exclusions)"},
            ],
            "effective_date": "1968 (amended regularly, major amendments in 2019)",
            "faq": [
                {"q": "Does the Employment Act cover managers and executives?", "a": "Yes, since the 2019 amendments. However, Part IV provisions (rest days, hours, overtime) only apply to workmen earning up to S$4,500/month and non-workmen earning up to S$2,600/month."},
                {"q": "What is the Employment Claims Tribunal?", "a": "A tribunal under the State Courts that handles salary-related disputes. Claims must first go through mediation at the Tripartite Alliance for Dispute Management (TADM)."},
            ],
            "case_examples": [
                "An employer fails to issue itemised payslips — this is an offence under the Employment Act.",
                "A non-workman earning S$2,400/month is denied overtime pay — this violates the Employment Act.",
            ],
        },
        {
            "id": "wsha",
            "title": "Workplace Safety & Health Act (WSHA)",
            "summary": "Requires employers to ensure a safe workplace and manage risks proactively.",
            "details": [
                "Employers must take reasonably practicable measures to ensure safety and health of workers.",
                "Risk assessments must be conducted for all work activities.",
                "Employees must be provided with adequate safety training and personal protective equipment.",
                "Workers have the right to report unsafe conditions to MOM without retaliation.",
                "Workplace injuries and dangerous occurrences must be reported to MOM.",
            ],
            "what_to_do": "Report hazards to your supervisor or safety officer. If unresolved, file a complaint with MOM's Occupational Safety and Health Division.",
            "enforcement_agency": "Ministry of Manpower — Occupational Safety and Health Division",
            "agency_contact": "6438 5122 | www.mom.gov.sg/workplace-safety-and-health",
            "penalties": [
                "Fines up to S$500,000 for employers.",
                "Imprisonment up to 2 years for serious breaches.",
                "Stop-work orders for imminent danger situations.",
            ],
            "key_laws": [
                {"name": "Workplace Safety and Health Act (WSHA)", "scope": "All workplaces in Singapore"},
            ],
            "effective_date": "2006",
        },
        {
            "id": "tafep",
            "title": "TAFEP Fair Employment Practices",
            "summary": "Guidelines against workplace discrimination enforced by the Tripartite Alliance for Fair & Progressive Employment Practices.",
            "details": [
                "Employers should not discriminate based on age, race, gender, religion, marital status, family responsibilities, or disability.",
                "Job advertisements must not state preference for any particular characteristic unless it is an inherent job requirement.",
                "Selection criteria should be based on skills, experience, and ability to perform the job.",
                "The Tripartite Guidelines on Fair Employment Practices (TGFEP) are enforceable under the Employment Act.",
                "The Workplace Fairness Act was passed in January 2025 and is expected to take effect in late 2027, providing statutory protections against workplace discrimination.",
            ],
            "what_to_do": "Report discriminatory practices to TAFEP (tafep.sg). You can file a complaint online or call the TAFEP hotline at 6838 0969.",
            "enforcement_agency": "Tripartite Alliance for Fair & Progressive Employment Practices (TAFEP)",
            "agency_contact": "6838 0969 | www.tafep.sg",
            "key_laws": [
                {"name": "Tripartite Guidelines on Fair Employment Practices (TGFEP)", "scope": "All employers in Singapore"},
                {"name": "Workplace Fairness Act 2025", "scope": "Statutory protections against workplace discrimination (effective late 2027)"},
            ],
            "effective_date": "TGFEP: 2007; Workplace Fairness Act: passed 2025, effective late 2027",
        },
        {
            "id": "poha",
            "title": "Protection from Harassment Act (POHA)",
            "summary": "Protects against harassment, bullying, and stalking in the workplace.",
            "details": [
                "Prohibits threatening, abusive, or insulting behaviour that causes harassment, alarm, or distress.",
                "Covers both physical and online harassment (cyberbullying).",
                "Victims can apply for Protection Orders or Expedited Protection Orders from the courts.",
                "Employers can be held liable for harassment by employees in the course of employment.",
                "Stalking, whether physical or through electronic means, is a criminal offence.",
            ],
            "what_to_do": "Document all incidents with screenshots, dates, and witnesses. Report to HR or management. You can apply for a Protection Order at the Protection from Harassment Court.",
            "enforcement_agency": "Protection from Harassment Court",
            "agency_contact": "judiciary.gov.sg | Police: 999 for emergencies",
            "key_laws": [
                {"name": "Protection from Harassment Act (POHA)", "scope": "All persons in Singapore; covers workplace and online harassment"},
            ],
            "effective_date": "2014 (amended 2019)",
        },
        {
            "id": "retirement",
            "title": "Retirement & Re-employment Act",
            "summary": "Protects older workers from premature retirement and ensures re-employment opportunities.",
            "details": [
                "Minimum retirement age is 64 years from 1 July 2026 (rising to 65 by 2030).",
                "Employers must offer re-employment to eligible employees up to age 69 from 1 July 2026 (rising to 70 by 2030).",
                "Re-employment must be on reasonable terms based on the employee's last drawn salary.",
                "Employers who cannot re-employ must offer an Employment Assistance Payment (EAP).",
                "Employers cannot dismiss employees to avoid re-employment obligations.",
            ],
            "what_to_do": "If you are approaching retirement age, request re-employment terms in writing. Disputes can be brought to MOM for mediation.",
            "enforcement_agency": "Ministry of Manpower (MOM)",
            "agency_contact": "6438 5122 | www.mom.gov.sg",
            "key_laws": [
                {"name": "Retirement and Re-employment Act (RRA)", "scope": "Singapore citizens and permanent residents"},
            ],
            "effective_date": "1993 (amended 2022)",
        },
        {
            "id": "efma",
            "title": "Employment of Foreign Manpower Act (EFMA)",
            "summary": "Regulates employment of foreign workers and protects their rights.",
            "details": [
                "Foreign workers must hold a valid work pass (Work Permit, S Pass, or Employment Pass).",
                "Employers must not collect or deduct kickbacks from foreign workers' salaries.",
                "Employers must provide acceptable accommodation and bear medical costs for Work Permit holders.",
                "Employers must purchase and maintain compulsory medical insurance for all Work Permit and S Pass holders, covering at least $15,000 per year for inpatient care and day surgery.",
                "Employers must also purchase personal accident insurance for Work Permit holders (minimum $40,000 for permanent disability or death).",
                "Foreign workers have the same Employment Act protections as local workers.",
                "Employers cannot hold workers' passports or restrict their movement.",
            ],
            "what_to_do": "Report violations to MOM. Foreign workers can seek help from the Migrant Workers' Centre (MWC) or call MOM's helpline at 6438 5122.",
            "enforcement_agency": "Ministry of Manpower (MOM)",
            "agency_contact": "6438 5122 | Migrant Workers' Centre: 6536 2692",
            "key_laws": [
                {"name": "Employment of Foreign Manpower Act (EFMA)", "scope": "All foreign workers in Singapore"},
            ],
            "effective_date": "1990 (amended regularly)",
        },
        {
            "id": "cpf",
            "title": "Central Provident Fund (CPF)",
            "summary": "Mandatory social security contributions for retirement, healthcare, and housing.",
            "details": [
                "Employers must make CPF contributions for Singapore citizens and permanent residents.",
                "Employer contribution rates: up to 17% of wages (varies by age group).",
                "Employee contribution rates: up to 20% of wages (varies by age group).",
                "CPF covers Ordinary Account (housing, education), Special Account (retirement), and MediSave (healthcare).",
                "Non-payment or late payment of CPF is a criminal offence.",
                "Employees can check their CPF contributions online via the CPF Board website.",
            ],
            "what_to_do": "Check your CPF statement regularly. If contributions are missing or incorrect, report to the CPF Board at 1800-227-1188.",
            "enforcement_agency": "Central Provident Fund Board",
            "agency_contact": "1800-227-1188 | www.cpf.gov.sg",
            "penalties": [
                "Late payment interest at 18% per annum on outstanding contributions.",
                "Fine up to S$5,000 and/or imprisonment up to 6 months per offence.",
                "Composition fines for late payments.",
            ],
            "key_laws": [
                {"name": "Central Provident Fund Act (Cap. 36)", "scope": "All employers with Singapore citizens and permanent residents"},
            ],
            "effective_date": "1953 (amended regularly)",
            "faq": [
                {"q": "Are CPF contributions required for part-time workers?", "a": "Yes, if the worker is a Singapore citizen or permanent resident. CPF contributions are based on actual wages earned."},
                {"q": "Do foreign workers receive CPF?", "a": "No, CPF contributions are only mandatory for Singapore citizens and permanent residents."},
            ],
        },
        {
            "id": "maternity",
            "title": "Maternity & Paternity Protections",
            "summary": "Paid maternity and paternity leave, childcare leave, and protection against dismissal during pregnancy.",
            "details": [
                "16 weeks of Government-Paid Maternity Leave (GPML) for eligible working mothers.",
                "4 weeks of Government-Paid Paternity Leave (GPPL) for eligible working fathers.",
                "6 days of paid childcare leave per year for each parent with children under 7.",
                "2 days of paid extended childcare leave per year for each parent with children aged 7-12.",
                "Employers cannot dismiss a female employee during maternity leave.",
                "Adoption leave of 12 weeks for qualifying adoptive mothers.",
                "Shared Parental Leave (SPL): 10 weeks shared between parents for children born from 1 April 2026 onwards (6 weeks for births from 1 April 2025 to 31 March 2026).",
            ],
            "what_to_do": "Notify your employer at least one week before the start of maternity leave. Ensure you meet eligibility requirements for government-paid leave (3+ months of employment, child is a Singapore citizen).",
            "enforcement_agency": "Ministry of Manpower (MOM)",
            "agency_contact": "6438 5122 | www.mom.gov.sg",
            "key_laws": [
                {"name": "Child Development Co-Savings Act", "scope": "Government-paid maternity, paternity, shared parental, and childcare leave"},
                {"name": "Employment Act (maternity provisions)", "scope": "Maternity leave and dismissal protections"},
            ],
            "effective_date": "Various — GPML: 2008, GPPL: 2017 (4 weeks mandatory from Apr 2025), SPL: Apr 2025",
            "faq": [
                {"q": "Am I eligible for 16 weeks of maternity leave?", "a": "You need to have worked for your employer for at least 3 months, and the child must be a Singapore citizen. Otherwise, you are entitled to 8 weeks under the Employment Act."},
            ],
        },
        {
            "id": "wrongful_dismissal",
            "title": "Wrongful Dismissal Protections",
            "summary": "Protection against unfair or wrongful termination of employment.",
            "details": [
                "Employees who feel they were dismissed without just or sufficient cause can file a wrongful dismissal claim.",
                "Claims must be filed with the Tripartite Alliance for Dispute Management (TADM) within one month of the last day of employment.",
                "Wrongful dismissal includes termination for exercising employment rights, discriminatory dismissal, and dismissal without cause.",
                "If mediation fails, the case can be referred to the Employment Claims Tribunal.",
                "Employees who have served at least 2 years of service (or less if pregnant / on national service) are eligible to claim.",
            ],
            "what_to_do": "File a mediation request at TADM within one month of dismissal. Bring your employment contract, termination letter, and any supporting documents.",
            "enforcement_agency": "Tripartite Alliance for Dispute Management (TADM) / Employment Claims Tribunal",
            "agency_contact": "TADM: 6838 0969 | www.tal.sg/tadm",
            "key_laws": [
                {"name": "Employment Act — Part IV on wrongful dismissal", "scope": "Employees covered under the Employment Act"},
            ],
            "effective_date": "2019 (wrongful dismissal provisions)",
            "faq": [
                {"q": "How long do I have to file a wrongful dismissal claim?", "a": "You must file with TADM within one month of the last day of employment."},
                {"q": "What remedies are available?", "a": "Reinstatement or compensation (capped at an amount equivalent to the salary you would have earned had you not been dismissed)."},
            ],
        },
        {
            "id": "industrial_relations_sg",
            "title": "Industrial Relations Act 1960",
            "summary": "Governs trade union recognition, collective bargaining, and industrial dispute resolution.",
            "details": [
                "Trade unions may seek recognition from employers to represent workers in collective bargaining.",
                "Once recognised, unions negotiate collective agreements covering wages, hours, and working conditions.",
                "Collective agreements must be for 2 to 3 years and certified by the Industrial Arbitration Court (IAC) to be enforceable.",
                "Disputes follow a three-tier process: collective bargaining, then MOM conciliation, then compulsory arbitration by the IAC.",
                "Industrial action (strikes/lockouts) is prohibited once a dispute has been referred to the IAC.",
                "Workers in essential services face additional restrictions on industrial action.",
                "Management retains prerogatives over promotion, transfer, hiring, and retrenchment, though unions may raise matters of a general character on these topics.",
            ],
            "what_to_do": "Contact MOM for conciliation services if collective bargaining breaks down. Trade union members can seek assistance from the National Trades Union Congress (NTUC).",
            "enforcement_agency": "Ministry of Manpower (MOM) / Industrial Arbitration Court (IAC)",
            "agency_contact": "MOM: 6438 5122 | NTUC: 6213 8008",
            "penalties": [
                "Illegal strikes: fine up to $2,000 and/or imprisonment up to 12 months.",
                "Employer refusal to recognise a union: MOM can direct recognition.",
                "Breach of collective agreement: enforceable through the IAC.",
            ],
            "key_laws": [
                {"name": "Industrial Relations Act 1960", "scope": "Collective bargaining, dispute resolution, and industrial action"},
                {"name": "Trade Unions Act (Cap. 333)", "scope": "Formation, registration, and governance of trade unions"},
            ],
            "effective_date": "1960 (amended regularly; major amendments in 1968)",
            "faq": [
                {"q": "Can I go on strike in Singapore?", "a": "Strikes are legal but prohibited once a dispute is referred to the IAC. Essential service workers face additional restrictions."},
                {"q": "How does my union get recognised?", "a": "The union applies to the employer for recognition. If refused, MOM may intervene and direct the employer to recognise the union."},
            ],
        },
    ],

    # ──────────────────────────────────────────────────────────────
    # MALAYSIA  (7 categories)
    # ──────────────────────────────────────────────────────────────
    "my": [
        {
            "id": "employment_act_1955",
            "title": "Employment Act 1955",
            "summary": "Malaysia's primary employment legislation governing wages, hours, leave, and termination.",
            "details": [
                "Applies to all employees regardless of salary (expanded coverage from 2023 amendments).",
                "Maximum 45 working hours per week. Overtime at 1.5x for normal days, 2x for rest days, 3x for public holidays.",
                "Minimum 8 days annual leave (increasing with years of service), 14 days paid sick leave, 60 days hospitalisation leave.",
                "Maternity leave of 98 days (increased from 60 days) for female employees.",
                "Paternity leave of 7 days for married male employees.",
                "Flexible working arrangement requests must be considered by employers (2023 amendment).",
                "Protection against sexual harassment in the workplace (Section 81H).",
            ],
            "what_to_do": "File complaints with the Labour Department (Jabatan Tenaga Kerja). For sexual harassment cases, lodge a complaint with the employer first, then the Director General of Labour.",
            "enforcement_agency": "Department of Labour (Jabatan Tenaga Kerja)",
            "agency_contact": "03-8886 5000 | jtksm.mohr.gov.my",
            "penalties": [
                "Fines up to RM50,000 per offence.",
                "Imprisonment up to 2 years for serious violations.",
                "Court orders to pay outstanding wages and benefits.",
            ],
            "key_laws": [
                {"name": "Employment Act 1955", "scope": "All employees under a contract of service (expanded in 2023)"},
                {"name": "Employment (Amendment) Act 2022", "scope": "Major amendments effective 2023 — flexible working, extended maternity leave"},
            ],
            "effective_date": "1955 (major amendments 2023)",
            "faq": [
                {"q": "Does the Employment Act cover all employees now?", "a": "Yes, since the 2023 amendments, the Act applies to all employees regardless of salary. Previously, it only fully covered employees earning RM2,000/month or less."},
                {"q": "Can I request flexible working arrangements?", "a": "Yes, under the 2023 amendments, employees can apply in writing. Employers must respond within 60 days."},
            ],
        },
        {
            "id": "industrial_relations",
            "title": "Industrial Relations Act 1967",
            "summary": "Governs employer-employee relations, trade unions, and dispute resolution.",
            "details": [
                "Employees have the right to join and form trade unions.",
                "Employers cannot interfere with or dismiss employees for union activities.",
                "Disputes can be referred to the Industrial Court for adjudication.",
                "Protection against unfair dismissal — employers must have just cause and follow due process.",
                "Collective bargaining agreements are legally binding.",
            ],
            "what_to_do": "Contact the Department of Industrial Relations to mediate disputes. Unfair dismissal claims should be filed within 60 days of termination.",
            "enforcement_agency": "Department of Industrial Relations / Industrial Court",
            "agency_contact": "03-8886 5000 | jpp.mohr.gov.my",
            "key_laws": [
                {"name": "Industrial Relations Act 1967", "scope": "All employers and employees; trade union rights and dispute resolution"},
            ],
            "effective_date": "1967 (amended regularly)",
            "faq": [
                {"q": "How long do I have to file an unfair dismissal claim?", "a": "You must file representations to the Director General of Industrial Relations within 60 days of your dismissal."},
            ],
        },
        {
            "id": "osha_1994",
            "title": "Occupational Safety & Health Act 1994 (OSHA)",
            "summary": "Ensures workplace safety and health standards for all industries.",
            "details": [
                "Employers must ensure, so far as practicable, the safety, health, and welfare of employees.",
                "Risk assessments must be conducted and safety measures implemented.",
                "Employers with 40+ employees must establish a Safety and Health Committee.",
                "Employees have the right to report unsafe conditions without retaliation.",
                "Workplace accidents and dangerous occurrences must be reported to DOSH.",
            ],
            "what_to_do": "Report hazards to your employer's Safety and Health Committee. If unresolved, contact the Department of Occupational Safety and Health (DOSH).",
            "enforcement_agency": "Department of Occupational Safety and Health (DOSH)",
            "agency_contact": "03-8886 5000 | www.dosh.gov.my",
            "key_laws": [
                {"name": "Occupational Safety and Health Act 1994", "scope": "All industries and workplaces in Malaysia"},
            ],
            "effective_date": "1994",
        },
        {
            "id": "minimum_wages",
            "title": "Minimum Wages",
            "summary": "National minimum wage requirements and compliance obligations for employers.",
            "details": [
                "National minimum wage of RM1,700 per month (effective February 2025) for all employers regardless of size.",
                "The minimum wage applies to all employees regardless of nationality.",
                "Employers cannot offset housing, food allowances, or other benefits against the minimum wage.",
                "Piece-rated workers must receive at least the minimum wage equivalent.",
                "The National Wages Consultative Council reviews and recommends minimum wage adjustments.",
            ],
            "what_to_do": "If you believe you are being paid below minimum wage, file a complaint with the nearest Labour Office. Keep your payslips as evidence.",
            "enforcement_agency": "Department of Labour (Jabatan Tenaga Kerja)",
            "agency_contact": "03-8886 5000 | jtksm.mohr.gov.my",
            "penalties": [
                "Fine up to RM10,000 per employee for each day the offence continues.",
                "Court orders to pay wage differences.",
            ],
            "key_laws": [
                {"name": "National Wages Consultative Council Act 2011", "scope": "All employers in Peninsular Malaysia, Sabah, Sarawak, and Labuan"},
                {"name": "Minimum Wages Order 2025", "scope": "Sets current minimum wage at RM1,700"},
            ],
            "effective_date": "2013 (first minimum wage); 2025 (RM1,700 rate)",
        },
        {
            "id": "social_security",
            "title": "Social Security (SOCSO / PERKESO)",
            "summary": "Mandatory social security coverage for employment injury, invalidity, and employment loss.",
            "details": [
                "All employees must be registered with SOCSO (PERKESO).",
                "Employment Injury Scheme: covers work-related accidents and occupational diseases.",
                "Invalidity Scheme: provides benefits for non-work-related invalidity or death.",
                "Employment Insurance System (EIS): provides temporary financial assistance for loss of employment.",
                "Both employer and employee contribute to SOCSO and EIS. Insurable salary ceiling is RM6,000/month (effective October 2024).",
                "Benefits include medical treatment, temporary/permanent disability benefits, dependants' benefits, and funeral benefits.",
            ],
            "what_to_do": "Verify your SOCSO registration with your employer. In case of workplace injury, report to your employer immediately and seek treatment at a SOCSO panel clinic.",
            "enforcement_agency": "Social Security Organisation (SOCSO / PERKESO)",
            "agency_contact": "1-300-22-8000 | www.perkeso.gov.my",
            "key_laws": [
                {"name": "Employees' Social Security Act 1969", "scope": "Employment injury and invalidity schemes"},
                {"name": "Employment Insurance System Act 2017", "scope": "Unemployment insurance / job loss assistance"},
            ],
            "effective_date": "1969 (SOCSO); 2018 (EIS)",
        },
        {
            "id": "anti_harassment",
            "title": "Anti-Sexual Harassment",
            "summary": "Legal protections against sexual harassment in the workplace.",
            "details": [
                "The Employment Act 1955 (Section 81H) requires employers to display a notice on sexual harassment.",
                "The Anti-Sexual Harassment Act 2022 provides a comprehensive legal framework.",
                "Covers physical, verbal, non-verbal, visual, and gesture-based harassment.",
                "Applies to all settings — workplace, public transport, educational institutions, and online.",
                "A Tribunal for Anti-Sexual Harassment handles complaints and can award compensation up to RM250,000.",
                "Employers must establish internal mechanisms to handle sexual harassment complaints.",
            ],
            "what_to_do": "Report to your employer's internal complaints mechanism first. If unsatisfied, file a complaint with the Tribunal for Anti-Sexual Harassment. You can also lodge a police report.",
            "enforcement_agency": "Tribunal for Anti-Sexual Harassment",
            "agency_contact": "Ministry of Women, Family and Community Development: 03-8000 8000",
            "key_laws": [
                {"name": "Anti-Sexual Harassment Act 2022", "scope": "All persons in Malaysia; comprehensive anti-harassment framework"},
                {"name": "Employment Act 1955 (Section 81H)", "scope": "Workplace sexual harassment protections"},
            ],
            "effective_date": "2022",
        },
        {
            "id": "foreign_workers",
            "title": "Foreign Worker Protections",
            "summary": "Rights and protections for foreign workers employed in Malaysia.",
            "details": [
                "Foreign workers have the same basic protections under the Employment Act 1955 as local workers.",
                "Employers must not retain workers' passports (this is a criminal offence).",
                "Foreign workers are entitled to minimum wage, overtime pay, annual leave, and sick leave.",
                "Employers must provide medical coverage (SPIKPA or private insurance) for foreign workers.",
                "Workers must hold valid work permits — employers are responsible for work permit costs.",
                "Forced labour and human trafficking are serious criminal offences under the Anti-Trafficking in Persons Act 2007.",
            ],
            "what_to_do": "Report passport confiscation or forced labour to the nearest police station or the National Human Rights Commission (SUHAKAM). For wage disputes, file a complaint at the Labour Department.",
            "enforcement_agency": "Immigration Department / Department of Labour / SUHAKAM",
            "agency_contact": "Labour Department: 03-8886 5000 | SUHAKAM: 03-2612 5600",
            "key_laws": [
                {"name": "Immigration Act 1959/63", "scope": "Work permits and immigration requirements"},
                {"name": "Anti-Trafficking in Persons and Anti-Smuggling of Migrants Act 2007", "scope": "Forced labour and trafficking protections"},
                {"name": "Passport Act 1966", "scope": "Prohibits retention of passports by employers"},
            ],
            "effective_date": "Various",
        },
    ],

    # ──────────────────────────────────────────────────────────────
    # INDONESIA  (5 categories)
    # ──────────────────────────────────────────────────────────────
    "id": [
        {
            "id": "omnibus_law",
            "title": "Omnibus Law on Job Creation (Law No. 6/2023)",
            "summary": "Indonesia's comprehensive employment reform covering wages, contracts, and severance.",
            "details": [
                "Minimum wage set by provincial governors based on economic conditions and purchasing power.",
                "Fixed-term employment contracts (PKWT) can be extended but limited to 5 years total.",
                "Severance pay required for termination: up to 9 months' salary depending on tenure.",
                "Outsourcing is permitted for supporting activities with worker protections maintained.",
                "Working hours: maximum 7 hours/day (6-day week) or 8 hours/day (5-day week), with overtime up to 4 hours/day and 18 hours/week.",
                "Overtime pay at 1.5x for the first hour and 2x for subsequent hours.",
                "Workers must receive two rest days per week for a 5-day work week.",
            ],
            "what_to_do": "File disputes with the local Manpower Office (Disnaker). Industrial disputes follow bipartite negotiation, then mediation, and finally the Industrial Relations Court.",
            "enforcement_agency": "Ministry of Manpower (Kemenaker) / Local Manpower Offices (Disnaker)",
            "agency_contact": "Kemenaker: (021) 5255 733 | kemnaker.go.id",
            "penalties": [
                "Administrative sanctions for non-compliance with minimum wage.",
                "Criminal sanctions: imprisonment up to 4 years and/or fine up to IDR 400 million for wage violations.",
                "Severance pay obligations enforceable through Industrial Relations Court.",
            ],
            "key_laws": [
                {"name": "Law No. 6/2023 on Job Creation (Omnibus Law)", "scope": "Comprehensive labour reform — wages, contracts, severance, outsourcing"},
                {"name": "Government Regulation No. 35/2021", "scope": "Implementing regulation on fixed-term contracts, outsourcing, working hours, and termination"},
            ],
            "effective_date": "2023 (replacing 2020 version after Constitutional Court ruling)",
        },
        {
            "id": "manpower_act",
            "title": "Manpower Act (Law No. 13/2003)",
            "summary": "Core labour law covering worker rights, social security, and workplace protections.",
            "details": [
                "Prohibition of child labour (under 15 years) with limited exceptions for light work.",
                "Equal opportunity and treatment without discrimination based on gender, ethnicity, race, religion, or political views.",
                "Female workers entitled to 3 months maternity leave, extendable to 6 months with medical certification (full pay months 1-4, 75% months 5-6 under Law 4/2024).",
                "Workers entitled to annual leave of at least 12 days after 12 months of continuous employment.",
                "Workers have the right to form and join trade unions.",
                "Employers must enrol workers in social security (BPJS Ketenagakerjaan and BPJS Kesehatan).",
            ],
            "what_to_do": "Report violations to the nearest Manpower Office. Workers can also seek assistance from trade unions or legal aid organisations.",
            "enforcement_agency": "Ministry of Manpower (Kemenaker)",
            "agency_contact": "Kemenaker: (021) 5255 733 | kemnaker.go.id",
            "key_laws": [
                {"name": "Law No. 13/2003 on Manpower", "scope": "Core labour law — as amended by the Omnibus Law"},
            ],
            "effective_date": "2003 (amended 2023)",
        },
        {
            "id": "social_security_bpjs",
            "title": "Social Security (BPJS)",
            "summary": "Mandatory social security programmes covering health, employment injury, retirement, and death benefits.",
            "details": [
                "BPJS Kesehatan: national health insurance covering workers and their families.",
                "BPJS Ketenagakerjaan covers four programmes: work accident insurance (JKK), death benefit (JKM), old-age savings (JHT), and pension (JP).",
                "All employers must register their workers in both BPJS programmes.",
                "Employer contributions: approximately 4% for health, 5.7% for employment benefits.",
                "JHT (old-age savings) can be withdrawn upon retirement, resignation after 5+ years, or in certain hardship situations.",
                "Work accident claims cover medical treatment, temporary disability, permanent disability, and death benefits.",
            ],
            "what_to_do": "Verify your BPJS registration through the BPJS mobile app or website. Report non-registration to the Manpower Office or BPJS directly.",
            "enforcement_agency": "BPJS Ketenagakerjaan / BPJS Kesehatan",
            "agency_contact": "BPJS Ketenagakerjaan: 175 | BPJS Kesehatan: 165",
            "penalties": [
                "Administrative sanctions: written warnings, fines, denial of certain public services.",
                "Criminal sanctions: imprisonment up to 8 years or fine up to IDR 1 billion for non-registration.",
            ],
            "key_laws": [
                {"name": "Law No. 24/2011 on BPJS", "scope": "National social security administrative body"},
                {"name": "Law No. 40/2004 on the National Social Security System", "scope": "Social security framework covering health, employment, and retirement"},
            ],
            "effective_date": "2014 (BPJS operational)",
        },
        {
            "id": "unions",
            "title": "Trade Unions & Collective Bargaining",
            "summary": "Workers' rights to organise, form unions, and engage in collective bargaining.",
            "details": [
                "Workers have the right to form trade unions with a minimum of 10 workers.",
                "Unions must be registered with the Manpower Office to be legally recognised.",
                "Employers cannot interfere with union formation or activities.",
                "Anti-union discrimination (dismissal, demotion, transfer) is prohibited.",
                "Collective labour agreements (PKB) are legally binding and valid for up to 2 years.",
                "The right to strike is protected, subject to legal procedures (failed negotiation and 7-day advance notice).",
            ],
            "what_to_do": "Contact the Manpower Office to register a new union. If facing anti-union actions, file a complaint with the Industrial Relations Court.",
            "enforcement_agency": "Ministry of Manpower / Industrial Relations Court",
            "agency_contact": "Kemenaker: (021) 5255 733",
            "key_laws": [
                {"name": "Law No. 21/2000 on Trade Unions", "scope": "Formation, registration, and rights of trade unions"},
                {"name": "Law No. 13/2003 on Manpower (Chapter XI)", "scope": "Collective bargaining and industrial relations"},
            ],
            "effective_date": "2000 (Trade Unions Act); 2003 (Manpower Act)",
        },
        {
            "id": "women_workers",
            "title": "Women Workers' Protections",
            "summary": "Special protections for female workers including maternity, menstrual leave, and night work.",
            "details": [
                "3 months of fully paid maternity leave, extendable to 6 months with medical certification (full pay months 1-4, 75% months 5-6 under Law 4/2024).",
                "Miscarriage leave of 1.5 months minimum, extendable with medical recommendation.",
                "Paternity leave of 2 days paid, extendable to 5 days with employer agreement. 2 days paid leave for miscarriage (Law 4/2024).",
                "2 days of menstrual leave per month (first and second day of menstruation).",
                "Female workers under 18 or pregnant women cannot be required to work between 11pm and 7am.",
                "Employers must provide transportation and adequate security for women working night shifts.",
                "Breastfeeding mothers must be given time and a private space to express milk during working hours.",
            ],
            "what_to_do": "Assert your rights under the Manpower Act. If denied, file a complaint with the Manpower Office or seek assistance from a legal aid organisation.",
            "enforcement_agency": "Ministry of Manpower (Kemenaker)",
            "agency_contact": "Kemenaker: (021) 5255 733 | Ministry of Women Empowerment: (021) 3842638",
            "key_laws": [
                {"name": "Law No. 13/2003 on Manpower (Articles 76-83)", "scope": "Special protections for female workers"},
                {"name": "Law No. 4/2024 on Mother and Child Healthcare", "scope": "Extended maternity leave, paternity leave, breastfeeding facilities"},
            ],
            "effective_date": "2003 (Manpower Act); 2024 (Law 4/2024)",
            "faq": [
                {"q": "Is menstrual leave mandatory?", "a": "Employers must grant menstrual leave if the employee feels pain and cannot work. No medical certificate is required, but company policies may vary."},
                {"q": "Is maternity leave fully paid?", "a": "Yes, the first 4 months are fully paid. If extended to 6 months with medical certification, months 5-6 are paid at 75% under Law 4/2024."},
            ],
        },
    ],

    # ──────────────────────────────────────────────────────────────
    # PHILIPPINES  (7 categories)
    # ──────────────────────────────────────────────────────────────
    "ph": [
        {
            "id": "labor_code",
            "title": "Labor Code of the Philippines",
            "summary": "Comprehensive law governing employment, wages, working conditions, and labour relations.",
            "details": [
                "Normal working hours: 8 hours per day. Overtime pay at 25% premium (30% for holidays/rest days).",
                "Minimum wage set by Regional Tripartite Wages and Productivity Boards.",
                "13th month pay mandatory for all rank-and-file employees.",
                "Service incentive leave of 5 days for employees who have worked at least 1 year.",
                "Maternity leave of 105 days (RA 11210). Paternity leave of 7 days.",
                "Night shift differential of at least 10% for work between 10pm and 6am.",
            ],
            "what_to_do": "File complaints with the Department of Labor and Employment (DOLE). For illegal dismissal, file a case with the National Labor Relations Commission (NLRC) within 4 years.",
            "enforcement_agency": "Department of Labor and Employment (DOLE)",
            "agency_contact": "DOLE Hotline: 1349 | www.dole.gov.ph",
            "penalties": [
                "Fines and/or imprisonment for labour standards violations.",
                "Back wages and reinstatement for illegal dismissal.",
                "Closure of non-compliant establishments.",
            ],
            "key_laws": [
                {"name": "Presidential Decree No. 442 (Labor Code)", "scope": "Comprehensive employment law — wages, hours, conditions, relations"},
                {"name": "RA 11210 (Expanded Maternity Leave Act)", "scope": "105 days of paid maternity leave"},
            ],
            "effective_date": "1974 (Labor Code); 2019 (Expanded Maternity Leave)",
        },
        {
            "id": "osh_standards",
            "title": "Occupational Safety & Health Standards Act (RA 11058)",
            "summary": "Strengthens workplace safety compliance and worker protections.",
            "details": [
                "Employers must provide a safe and healthy workplace at no cost to workers.",
                "Mandatory safety officers and safety committees for establishments with threshold number of workers.",
                "Workers have the right to refuse unsafe work without threat of retaliation.",
                "Employers must report work accidents, occupational diseases, and dangerous occurrences to DOLE.",
                "Workers must receive free OSH training appropriate to their job.",
                "Penalties for non-compliance include fines and possible closure of establishment.",
            ],
            "what_to_do": "Report workplace hazards to your safety officer or DOLE regional office. You can also call the DOLE hotline 1349.",
            "enforcement_agency": "DOLE — Bureau of Working Conditions",
            "agency_contact": "DOLE Hotline: 1349 | www.dole.gov.ph",
            "key_laws": [
                {"name": "RA 11058 (Occupational Safety and Health Standards Act)", "scope": "All workplaces in the Philippines"},
            ],
            "effective_date": "2018",
        },
        {
            "id": "security_of_tenure",
            "title": "Security of Tenure",
            "summary": "Every employee has the right to security of tenure — termination only for just or authorized causes.",
            "details": [
                "Employees can only be dismissed for just causes (serious misconduct, wilful disobedience, gross neglect, fraud, crime) or authorized causes (redundancy, retrenchment, closure, disease).",
                "Two-notice rule: employees must receive a written notice of charges and a notice of decision after hearing.",
                "Constructive dismissal (demotion, unbearable conditions forcing resignation) is treated as illegal dismissal.",
                "Probationary employees can be terminated for failing to meet reasonable standards communicated at the start.",
                "Illegal dismissal: employee is entitled to reinstatement and full back wages.",
                "Separation pay is required for authorized cause terminations (typically 1 month per year of service).",
            ],
            "what_to_do": "If you believe you were illegally dismissed, file a complaint with the NLRC within 4 years. Gather your employment contract, notice of termination, and any related communications.",
            "enforcement_agency": "National Labor Relations Commission (NLRC)",
            "agency_contact": "NLRC: (02) 8527-3000 | nlrc.dole.gov.ph",
            "key_laws": [
                {"name": "Labor Code, Article 294 (formerly 279)", "scope": "Right to security of tenure; reinstatement for illegal dismissal"},
                {"name": "Labor Code, Articles 297-299", "scope": "Just and authorized causes for termination"},
            ],
            "effective_date": "1974",
            "faq": [
                {"q": "What is the two-notice rule?", "a": "First notice: inform the employee of the specific acts or omissions. Second notice: inform of the employer's decision after giving the employee a chance to be heard."},
                {"q": "What is constructive dismissal?", "a": "When an employer makes working conditions so unbearable that a reasonable person would feel compelled to resign. This is treated as illegal dismissal."},
            ],
        },
        {
            "id": "social_benefits",
            "title": "Social Benefits (SSS, PhilHealth, Pag-IBIG)",
            "summary": "Mandatory social security, health insurance, and housing fund contributions for all employees.",
            "details": [
                "SSS (Social Security System): provides sickness, maternity, disability, retirement, death, and funeral benefits. Contribution rate: 15% (10% employer + 5% employee) with maximum monthly salary credit of ₱35,000.",
                "PhilHealth: national health insurance providing inpatient and outpatient coverage. Premium rate: 5% of monthly salary (effective January 2025).",
                "Pag-IBIG (HDMF): housing fund with savings programme and housing loan access.",
                "Both employer and employee make monthly contributions to all three programmes.",
                "Self-employed individuals and voluntary members can also participate.",
                "Non-remittance of contributions by employer is a criminal offence.",
            ],
            "what_to_do": "Verify your contributions through the SSS, PhilHealth, and Pag-IBIG online portals or mobile apps. Report non-remittance to the respective agency.",
            "enforcement_agency": "SSS / PhilHealth / Pag-IBIG Fund (HDMF)",
            "agency_contact": "SSS: 1455 | PhilHealth: (02) 8441-7442 | Pag-IBIG: (02) 8724-4244",
            "key_laws": [
                {"name": "RA 11199 (Social Security Act of 2018)", "scope": "SSS coverage, benefits, and contributions"},
                {"name": "RA 11223 (Universal Health Care Act)", "scope": "PhilHealth — automatic enrolment for all Filipinos"},
                {"name": "RA 9679 (Home Development Mutual Fund Law)", "scope": "Pag-IBIG Fund — mandatory membership and contributions"},
            ],
            "effective_date": "Various — SSS: 2019, PhilHealth UHC: 2019, Pag-IBIG: 2009",
        },
        {
            "id": "anti_harassment_ph",
            "title": "Anti-Sexual Harassment & Safe Spaces",
            "summary": "Legal protections against sexual harassment in the workplace and public spaces.",
            "details": [
                "RA 7877 (Anti-Sexual Harassment Act): prohibits sexual harassment by persons of authority in work, education, and training environments.",
                "RA 11313 (Safe Spaces Act / Bawal Bastos Law): covers gender-based sexual harassment in streets, public spaces, online, and workplaces.",
                "Employers must create a Committee on Decorum and Investigation (CODI) to handle harassment complaints.",
                "Penalties include fines, imprisonment, community service, and mandatory gender sensitivity training.",
                "Employer liability if they fail to act on reported harassment.",
                "Protection extends to all genders and covers both physical and online harassment.",
            ],
            "what_to_do": "Report to your company's CODI. If your employer does not have one, file a complaint directly with the DOLE or the local police station.",
            "enforcement_agency": "DOLE / Philippine Commission on Women / Local Government Units",
            "agency_contact": "DOLE Hotline: 1349 | PCW: (02) 8735-1654",
            "key_laws": [
                {"name": "RA 7877 (Anti-Sexual Harassment Act of 1995)", "scope": "Sexual harassment in work, education, and training"},
                {"name": "RA 11313 (Safe Spaces Act of 2019)", "scope": "Gender-based harassment in public spaces, workplaces, and online"},
            ],
            "effective_date": "1995 (RA 7877); 2019 (RA 11313)",
        },
        {
            "id": "wages_benefits",
            "title": "Wages & Mandatory Benefits",
            "summary": "Minimum wage, 13th month pay, holiday pay, and other mandatory monetary benefits.",
            "details": [
                "Minimum wage varies by region, set by Regional Tripartite Wages and Productivity Boards.",
                "13th month pay: mandatory for all rank-and-file employees, due on or before December 24.",
                "Holiday pay: 200% of daily wage for regular holidays worked; 130% for special non-working days.",
                "Service incentive leave: 5 days paid leave per year (convertible to cash if unused).",
                "Separation pay for authorized-cause terminations: typically 1/2 to 1 month per year of service.",
                "Retirement pay: at least 1/2 month salary per year of service for employees who retire at age 60-65 (if no CBA or retirement plan).",
            ],
            "what_to_do": "File wage-related complaints with the DOLE regional office or the NLRC. Keep copies of your payslips and employment contract.",
            "enforcement_agency": "Department of Labor and Employment (DOLE)",
            "agency_contact": "DOLE Hotline: 1349 | NLRC: (02) 8527-3000",
            "penalties": [
                "Non-payment of 13th month pay: fine of PHP 25,000 to PHP 100,000 and/or imprisonment.",
                "Minimum wage violations: fine and/or imprisonment.",
                "Double indemnity for underpayment of wages under RA 8188.",
            ],
            "key_laws": [
                {"name": "RA 6727 (Wage Rationalization Act)", "scope": "Regional minimum wage setting"},
                {"name": "PD 851 (13th Month Pay Law)", "scope": "Mandatory 13th month pay for rank-and-file employees"},
                {"name": "Labor Code, Book III", "scope": "Conditions of employment — wages, hours, benefits"},
            ],
            "effective_date": "Various — Wage Act: 1989, 13th Month: 1975",
        },
        {
            "id": "labor_relations_ph",
            "title": "Labor Relations & Collective Bargaining",
            "summary": "Workers' rights to self-organisation, union formation, collective bargaining, and lawful strikes.",
            "details": [
                "Workers have the right to self-organisation and to form, join, or assist labour unions (Labor Code, Book V).",
                "A certified exclusive bargaining agent negotiates collective bargaining agreements (CBAs) with the employer.",
                "CBAs are valid for 5 years, with economic provisions renegotiable after 3 years.",
                "Employer unfair labour practices include interference with union activity, discrimination for union membership, and refusal to bargain.",
                "Union unfair labour practices include restraining employees' right to self-organise and refusing to bargain in good faith.",
                "Strike notice: 30 days for bargaining deadlocks, 15 days for unfair labour practice strikes.",
                "A strike vote must be approved by a majority of union members by secret ballot.",
                "Disputes go through grievance machinery, then voluntary arbitration, then NCMB conciliation, then NLRC compulsory arbitration.",
            ],
            "what_to_do": "Contact the National Conciliation and Mediation Board (NCMB) for dispute mediation. File unfair labour practice complaints with the NLRC.",
            "enforcement_agency": "National Labor Relations Commission (NLRC) / National Conciliation and Mediation Board (NCMB)",
            "agency_contact": "NLRC: (02) 8527-3000 | NCMB: (02) 8527-3485 | DOLE Hotline: 1349",
            "penalties": [
                "Illegal strikes: criminal liability for union officers who knowingly participate.",
                "Unfair labour practices: reinstatement, back wages, and damages.",
                "Illegal lockouts: penalties equivalent to those for illegal strikes.",
            ],
            "key_laws": [
                {"name": "Labor Code, Book V (Labor Relations)", "scope": "Union rights, collective bargaining, strikes, and dispute resolution"},
                {"name": "RA 6715 (Herrera-Veloso Law, 1989)", "scope": "Strengthened workers' rights to self-organisation and collective bargaining"},
            ],
            "effective_date": "1974 (Labor Code); 1989 (RA 6715)",
            "faq": [
                {"q": "How many workers are needed to form a union?", "a": "At least 20% of employees in the bargaining unit must support the petition for union registration."},
                {"q": "Can my employer prevent me from joining a union?", "a": "No. Interference with union rights is an unfair labour practice punishable under the Labor Code."},
            ],
        },
    ],

    # ──────────────────────────────────────────────────────────────
    # THAILAND  (5 categories)
    # ──────────────────────────────────────────────────────────────
    "th": [
        {
            "id": "labor_protection",
            "title": "Labor Protection Act B.E. 2541 (1998)",
            "summary": "Thailand's primary labour law covering wages, hours, leave, and termination protections.",
            "details": [
                "Normal working hours: maximum 8 hours/day and 48 hours/week. Overtime at 1.5x rate.",
                "Minimum wage set by the National Wage Committee (varies by province).",
                "Annual leave of at least 6 working days after 1 year of service.",
                "Sick leave up to 30 working days per year with pay (medical certificate required after 3 days).",
                "Maternity leave of 120 days (60 days paid by employer, remainder by Social Security) — increased from 98 days under LPA No. 9 (effective December 2025).",
                "Paternity leave of 15 days at full pay (LPA No. 9, effective December 2025).",
                "Severance pay required for termination: 30 days to 400 days of wages depending on tenure.",
                "Employers cannot dismiss employees for exercising legal rights, filing complaints, or union activities.",
            ],
            "what_to_do": "File complaints with the Labour Protection and Welfare Office in your province. Disputes can be escalated to the Labour Court.",
            "enforcement_agency": "Department of Labour Protection and Welfare (DLPW)",
            "agency_contact": "Hotline: 1506 | www.labour.go.th",
            "penalties": [
                "Fines up to THB 200,000 for violating labour protection standards.",
                "Imprisonment up to 1 year for serious offences.",
                "Court orders to pay outstanding wages and severance.",
            ],
            "key_laws": [
                {"name": "Labor Protection Act B.E. 2541 (1998)", "scope": "All employers and employees in Thailand (with limited exclusions)"},
                {"name": "Labor Protection Act (No. 7) B.E. 2562 (2019)", "scope": "Amendments — increased severance pay tier"},
                {"name": "Labor Protection Act (No. 9) B.E. 2568 (2025)", "scope": "Amendments — maternity leave increased to 120 days, 15-day paternity leave"},
            ],
            "effective_date": "1998 (amended 2019, 2025)",
        },
        {
            "id": "labor_relations",
            "title": "Labor Relations Act B.E. 2518 (1975)",
            "summary": "Governs collective bargaining, trade unions, and labour dispute resolution.",
            "details": [
                "Employees have the right to form and join trade unions and employee committees.",
                "Employers cannot terminate, reduce wages, or take adverse action against union members.",
                "Labour disputes follow a defined process: negotiation, conciliation, then the Labour Relations Committee.",
                "Strikes and lockouts are permitted only after following the legal dispute resolution process.",
                "Employee committees (with 50+ employees) can negotiate working conditions with employers.",
            ],
            "what_to_do": "Contact the Department of Labour Protection and Welfare. For unfair labour practices, file a complaint with the Labour Relations Committee.",
            "enforcement_agency": "Labour Relations Committee / Department of Labour Protection and Welfare",
            "agency_contact": "Hotline: 1506 | www.labour.go.th",
            "key_laws": [
                {"name": "Labor Relations Act B.E. 2518 (1975)", "scope": "Private-sector labour relations, unions, and collective bargaining"},
            ],
            "effective_date": "1975",
        },
        {
            "id": "social_security_th",
            "title": "Social Security",
            "summary": "Mandatory social insurance covering sickness, maternity, disability, death, child allowance, old age, and unemployment.",
            "details": [
                "All employers with 1 or more employees must register with the Social Security Office (SSO).",
                "Both employer and employee contribute 5% of wages (capped at THB 17,500/month from January 2026) each.",
                "Government also contributes a portion to the fund.",
                "Benefits cover 7 categories: sickness, maternity, invalidity, death, child allowance, old-age pension, and unemployment.",
                "Maternity benefit: 90 days of wages at 50% from the Social Security Fund (in addition to 60 days from employer).",
                "Old-age pension payable from age 55 after at least 180 months of contributions.",
                "Unemployment benefits: up to 50% of wages for up to 6 months (for involuntary separation).",
            ],
            "what_to_do": "Verify your Social Security registration and contribution history through the SSO website or app. Report non-registration to the SSO or Labour Protection Office.",
            "enforcement_agency": "Social Security Office (SSO)",
            "agency_contact": "Hotline: 1506 | www.sso.go.th",
            "penalties": [
                "Fines up to THB 20,000 for non-registration.",
                "Imprisonment up to 6 months and/or fines for non-payment of contributions.",
                "2% per month surcharge on late contributions.",
            ],
            "key_laws": [
                {"name": "Social Security Act B.E. 2533 (1990)", "scope": "All employers and employees in Thailand"},
            ],
            "effective_date": "1990 (expanded coverage progressively)",
        },
        {
            "id": "foreign_workers_th",
            "title": "Foreign Worker Protections",
            "summary": "Regulations governing the employment of foreign workers in Thailand.",
            "details": [
                "Foreign workers must hold a valid work permit under the Royal Ordinance on Management of Employment of Foreign Workers B.E. 2560 (2017).",
                "Certain occupations are reserved for Thai nationals (20 strictly prohibited occupations per 2022 DOE Notification).",
                "Foreign workers have the same labour protection rights as Thai workers under the Labor Protection Act.",
                "Employers must not confiscate passports or work permits.",
                "MOU workers from Myanmar, Laos, Cambodia, and Vietnam have specific import/regularisation processes.",
                "Anti-trafficking protections: employers and brokers who engage in forced labour face severe criminal penalties.",
            ],
            "what_to_do": "Report work permit violations or forced labour to the nearest Labour Protection Office or call the Anti-Human Trafficking Hotline at 1300.",
            "enforcement_agency": "Department of Employment / Department of Labour Protection and Welfare",
            "agency_contact": "Hotline: 1506 | Anti-Trafficking: 1300",
            "key_laws": [
                {"name": "Royal Ordinance on Management of Employment of Foreign Workers B.E. 2560 (2017)", "scope": "Work permits and employment of foreign workers"},
                {"name": "Anti-Trafficking in Persons Act B.E. 2551 (2008)", "scope": "Forced labour and human trafficking protections"},
            ],
            "effective_date": "2017 (Royal Ordinance); 2022 (revised occupation list)",
        },
        {
            "id": "workplace_harassment_th",
            "title": "Workplace Harassment Protections",
            "summary": "Protections against sexual harassment and bullying in the workplace.",
            "details": [
                "The Labor Protection Act prohibits sexual harassment by employers, supervisors, or work inspectors against employees.",
                "Sexual harassment includes unwelcome sexual advances, requests for sexual favours, and other verbal or physical conduct of a sexual nature.",
                "Victims can terminate employment and claim severance and damages if subjected to sexual harassment by the employer.",
                "The Gender Equality Act B.E. 2558 (2015) prohibits gender-based discrimination in employment.",
                "Complaints of gender discrimination can be filed with the Committee on the Consideration of Unfair Gender Discrimination.",
                "Employers who fail to prevent or address harassment may face civil liability for damages.",
            ],
            "what_to_do": "Report to your employer or HR department first. If unresolved, file a complaint with the Labour Protection Office or report to the police. For gender discrimination, contact the Department of Women's Affairs and Family Development.",
            "enforcement_agency": "Department of Labour Protection and Welfare / Committee on Unfair Gender Discrimination",
            "agency_contact": "Hotline: 1506 | Women's Affairs: 1300",
            "key_laws": [
                {"name": "Labor Protection Act B.E. 2541 (Section 16)", "scope": "Prohibition of sexual harassment by employers and supervisors"},
                {"name": "Gender Equality Act B.E. 2558 (2015)", "scope": "Gender-based discrimination in employment and public services"},
            ],
            "effective_date": "1998 (LPA); 2015 (Gender Equality Act)",
        },
    ],
}
